//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("NSCModel", "FK_SX02_USER_SX01_AREA", "SX01_AREA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NSC.SX01_AREA), "SX02_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NSC.SX02_USER), true)]
[assembly: EdmRelationshipAttribute("NSCModel", "FK_SX02_USER_SX03_DEPT", "SX03_DEPT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NSC.SX03_DEPT), "SX02_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NSC.SX02_USER), true)]

#endregion

namespace NSC
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class NSCEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“NSCEntities”部分中的连接字符串初始化新 NSCEntities 对象。
        /// </summary>
        public NSCEntities() : base("name=NSCEntities", "NSCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 NSCEntities 对象。
        /// </summary>
        public NSCEntities(string connectionString) : base(connectionString, "NSCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 NSCEntities 对象。
        /// </summary>
        public NSCEntities(EntityConnection connection) : base(connection, "NSCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<DT01> DT01
        {
            get
            {
                if ((_DT01 == null))
                {
                    _DT01 = base.CreateObjectSet<DT01>("DT01");
                }
                return _DT01;
            }
        }
        private ObjectSet<DT01> _DT01;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<DT02> DT02
        {
            get
            {
                if ((_DT02 == null))
                {
                    _DT02 = base.CreateObjectSet<DT02>("DT02");
                }
                return _DT02;
            }
        }
        private ObjectSet<DT02> _DT02;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<DT03> DT03
        {
            get
            {
                if ((_DT03 == null))
                {
                    _DT03 = base.CreateObjectSet<DT03>("DT03");
                }
                return _DT03;
            }
        }
        private ObjectSet<DT03> _DT03;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SX04_SYS> SX04_SYS
        {
            get
            {
                if ((_SX04_SYS == null))
                {
                    _SX04_SYS = base.CreateObjectSet<SX04_SYS>("SX04_SYS");
                }
                return _SX04_SYS;
            }
        }
        private ObjectSet<SX04_SYS> _SX04_SYS;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SX02_USER> SX02_USER
        {
            get
            {
                if ((_SX02_USER == null))
                {
                    _SX02_USER = base.CreateObjectSet<SX02_USER>("SX02_USER");
                }
                return _SX02_USER;
            }
        }
        private ObjectSet<SX02_USER> _SX02_USER;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SX01_AREA> SX01_AREA
        {
            get
            {
                if ((_SX01_AREA == null))
                {
                    _SX01_AREA = base.CreateObjectSet<SX01_AREA>("SX01_AREA");
                }
                return _SX01_AREA;
            }
        }
        private ObjectSet<SX01_AREA> _SX01_AREA;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SX03_DEPT> SX03_DEPT
        {
            get
            {
                if ((_SX03_DEPT == null))
                {
                    _SX03_DEPT = base.CreateObjectSet<SX03_DEPT>("SX03_DEPT");
                }
                return _SX03_DEPT;
            }
        }
        private ObjectSet<SX03_DEPT> _SX03_DEPT;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<DT04> DT04
        {
            get
            {
                if ((_DT04 == null))
                {
                    _DT04 = base.CreateObjectSet<DT04>("DT04");
                }
                return _DT04;
            }
        }
        private ObjectSet<DT04> _DT04;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 DT01 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToDT01(DT01 dT01)
        {
            base.AddObject("DT01", dT01);
        }
    
        /// <summary>
        /// 用于向 DT02 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToDT02(DT02 dT02)
        {
            base.AddObject("DT02", dT02);
        }
    
        /// <summary>
        /// 用于向 DT03 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToDT03(DT03 dT03)
        {
            base.AddObject("DT03", dT03);
        }
    
        /// <summary>
        /// 用于向 SX04_SYS EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSX04_SYS(SX04_SYS sX04_SYS)
        {
            base.AddObject("SX04_SYS", sX04_SYS);
        }
    
        /// <summary>
        /// 用于向 SX02_USER EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSX02_USER(SX02_USER sX02_USER)
        {
            base.AddObject("SX02_USER", sX02_USER);
        }
    
        /// <summary>
        /// 用于向 SX01_AREA EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSX01_AREA(SX01_AREA sX01_AREA)
        {
            base.AddObject("SX01_AREA", sX01_AREA);
        }
    
        /// <summary>
        /// 用于向 SX03_DEPT EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSX03_DEPT(SX03_DEPT sX03_DEPT)
        {
            base.AddObject("SX03_DEPT", sX03_DEPT);
        }
    
        /// <summary>
        /// 用于向 DT04 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToDT04(DT04 dT04)
        {
            base.AddObject("DT04", dT04);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="DT01")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DT01 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 DT01 对象。
        /// </summary>
        /// <param name="d01">D01 属性的初始值。</param>
        /// <param name="d99">D99 属性的初始值。</param>
        public static DT01 CreateDT01(global::System.Int32 d01, global::System.Byte d99)
        {
            DT01 dT01 = new DT01();
            dT01.D01 = d01;
            dT01.D99 = d99;
            return dT01;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 D01
        {
            get
            {
                return _D01;
            }
            set
            {
                if (_D01 != value)
                {
                    OnD01Changing(value);
                    ReportPropertyChanging("D01");
                    _D01 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("D01");
                    OnD01Changed();
                }
            }
        }
        private global::System.Int32 _D01;
        partial void OnD01Changing(global::System.Int32 value);
        partial void OnD01Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D02
        {
            get
            {
                return _D02;
            }
            set
            {
                OnD02Changing(value);
                ReportPropertyChanging("D02");
                _D02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D02");
                OnD02Changed();
            }
        }
        private global::System.String _D02;
        partial void OnD02Changing(global::System.String value);
        partial void OnD02Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D03
        {
            get
            {
                return _D03;
            }
            set
            {
                OnD03Changing(value);
                ReportPropertyChanging("D03");
                _D03 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D03");
                OnD03Changed();
            }
        }
        private Nullable<global::System.DateTime> _D03;
        partial void OnD03Changing(Nullable<global::System.DateTime> value);
        partial void OnD03Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D04
        {
            get
            {
                return _D04;
            }
            set
            {
                OnD04Changing(value);
                ReportPropertyChanging("D04");
                _D04 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D04");
                OnD04Changed();
            }
        }
        private global::System.String _D04;
        partial void OnD04Changing(global::System.String value);
        partial void OnD04Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D05
        {
            get
            {
                return _D05;
            }
            set
            {
                OnD05Changing(value);
                ReportPropertyChanging("D05");
                _D05 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D05");
                OnD05Changed();
            }
        }
        private global::System.String _D05;
        partial void OnD05Changing(global::System.String value);
        partial void OnD05Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte D99
        {
            get
            {
                return _D99;
            }
            set
            {
                OnD99Changing(value);
                ReportPropertyChanging("D99");
                _D99 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D99");
                OnD99Changed();
            }
        }
        private global::System.Byte _D99;
        partial void OnD99Changing(global::System.Byte value);
        partial void OnD99Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="DT02")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DT02 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 DT02 对象。
        /// </summary>
        /// <param name="d01">D01 属性的初始值。</param>
        /// <param name="d99">D99 属性的初始值。</param>
        public static DT02 CreateDT02(global::System.Int32 d01, global::System.Byte d99)
        {
            DT02 dT02 = new DT02();
            dT02.D01 = d01;
            dT02.D99 = d99;
            return dT02;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 D01
        {
            get
            {
                return _D01;
            }
            set
            {
                if (_D01 != value)
                {
                    OnD01Changing(value);
                    ReportPropertyChanging("D01");
                    _D01 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("D01");
                    OnD01Changed();
                }
            }
        }
        private global::System.Int32 _D01;
        partial void OnD01Changing(global::System.Int32 value);
        partial void OnD01Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D02
        {
            get
            {
                return _D02;
            }
            set
            {
                OnD02Changing(value);
                ReportPropertyChanging("D02");
                _D02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D02");
                OnD02Changed();
            }
        }
        private global::System.String _D02;
        partial void OnD02Changing(global::System.String value);
        partial void OnD02Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D03
        {
            get
            {
                return _D03;
            }
            set
            {
                OnD03Changing(value);
                ReportPropertyChanging("D03");
                _D03 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D03");
                OnD03Changed();
            }
        }
        private Nullable<global::System.DateTime> _D03;
        partial void OnD03Changing(Nullable<global::System.DateTime> value);
        partial void OnD03Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D04
        {
            get
            {
                return _D04;
            }
            set
            {
                OnD04Changing(value);
                ReportPropertyChanging("D04");
                _D04 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D04");
                OnD04Changed();
            }
        }
        private global::System.String _D04;
        partial void OnD04Changing(global::System.String value);
        partial void OnD04Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D05
        {
            get
            {
                return _D05;
            }
            set
            {
                OnD05Changing(value);
                ReportPropertyChanging("D05");
                _D05 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D05");
                OnD05Changed();
            }
        }
        private global::System.String _D05;
        partial void OnD05Changing(global::System.String value);
        partial void OnD05Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte D99
        {
            get
            {
                return _D99;
            }
            set
            {
                OnD99Changing(value);
                ReportPropertyChanging("D99");
                _D99 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D99");
                OnD99Changed();
            }
        }
        private global::System.Byte _D99;
        partial void OnD99Changing(global::System.Byte value);
        partial void OnD99Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="DT03")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DT03 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 DT03 对象。
        /// </summary>
        /// <param name="d01">D01 属性的初始值。</param>
        /// <param name="d99">D99 属性的初始值。</param>
        public static DT03 CreateDT03(global::System.Int32 d01, global::System.Byte d99)
        {
            DT03 dT03 = new DT03();
            dT03.D01 = d01;
            dT03.D99 = d99;
            return dT03;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 D01
        {
            get
            {
                return _D01;
            }
            set
            {
                if (_D01 != value)
                {
                    OnD01Changing(value);
                    ReportPropertyChanging("D01");
                    _D01 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("D01");
                    OnD01Changed();
                }
            }
        }
        private global::System.Int32 _D01;
        partial void OnD01Changing(global::System.Int32 value);
        partial void OnD01Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D02
        {
            get
            {
                return _D02;
            }
            set
            {
                OnD02Changing(value);
                ReportPropertyChanging("D02");
                _D02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D02");
                OnD02Changed();
            }
        }
        private global::System.String _D02;
        partial void OnD02Changing(global::System.String value);
        partial void OnD02Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D03
        {
            get
            {
                return _D03;
            }
            set
            {
                OnD03Changing(value);
                ReportPropertyChanging("D03");
                _D03 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D03");
                OnD03Changed();
            }
        }
        private Nullable<global::System.DateTime> _D03;
        partial void OnD03Changing(Nullable<global::System.DateTime> value);
        partial void OnD03Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D04
        {
            get
            {
                return _D04;
            }
            set
            {
                OnD04Changing(value);
                ReportPropertyChanging("D04");
                _D04 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D04");
                OnD04Changed();
            }
        }
        private global::System.String _D04;
        partial void OnD04Changing(global::System.String value);
        partial void OnD04Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D05
        {
            get
            {
                return _D05;
            }
            set
            {
                OnD05Changing(value);
                ReportPropertyChanging("D05");
                _D05 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D05");
                OnD05Changed();
            }
        }
        private global::System.String _D05;
        partial void OnD05Changing(global::System.String value);
        partial void OnD05Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte D99
        {
            get
            {
                return _D99;
            }
            set
            {
                OnD99Changing(value);
                ReportPropertyChanging("D99");
                _D99 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D99");
                OnD99Changed();
            }
        }
        private global::System.Byte _D99;
        partial void OnD99Changing(global::System.Byte value);
        partial void OnD99Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="DT04")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DT04 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 DT04 对象。
        /// </summary>
        /// <param name="d01">D01 属性的初始值。</param>
        /// <param name="d99">D99 属性的初始值。</param>
        public static DT04 CreateDT04(global::System.Int32 d01, global::System.Byte d99)
        {
            DT04 dT04 = new DT04();
            dT04.D01 = d01;
            dT04.D99 = d99;
            return dT04;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 D01
        {
            get
            {
                return _D01;
            }
            set
            {
                if (_D01 != value)
                {
                    OnD01Changing(value);
                    ReportPropertyChanging("D01");
                    _D01 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("D01");
                    OnD01Changed();
                }
            }
        }
        private global::System.Int32 _D01;
        partial void OnD01Changing(global::System.Int32 value);
        partial void OnD01Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DD1
        {
            get
            {
                return _DD1;
            }
            set
            {
                OnDD1Changing(value);
                ReportPropertyChanging("DD1");
                _DD1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DD1");
                OnDD1Changed();
            }
        }
        private global::System.String _DD1;
        partial void OnDD1Changing(global::System.String value);
        partial void OnDD1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DD2
        {
            get
            {
                return _DD2;
            }
            set
            {
                OnDD2Changing(value);
                ReportPropertyChanging("DD2");
                _DD2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DD2");
                OnDD2Changed();
            }
        }
        private global::System.String _DD2;
        partial void OnDD2Changing(global::System.String value);
        partial void OnDD2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> D02
        {
            get
            {
                return _D02;
            }
            set
            {
                OnD02Changing(value);
                ReportPropertyChanging("D02");
                _D02 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D02");
                OnD02Changed();
            }
        }
        private Nullable<global::System.Int32> _D02;
        partial void OnD02Changing(Nullable<global::System.Int32> value);
        partial void OnD02Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D03
        {
            get
            {
                return _D03;
            }
            set
            {
                OnD03Changing(value);
                ReportPropertyChanging("D03");
                _D03 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D03");
                OnD03Changed();
            }
        }
        private Nullable<global::System.DateTime> _D03;
        partial void OnD03Changing(Nullable<global::System.DateTime> value);
        partial void OnD03Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D04
        {
            get
            {
                return _D04;
            }
            set
            {
                OnD04Changing(value);
                ReportPropertyChanging("D04");
                _D04 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D04");
                OnD04Changed();
            }
        }
        private global::System.String _D04;
        partial void OnD04Changing(global::System.String value);
        partial void OnD04Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D05
        {
            get
            {
                return _D05;
            }
            set
            {
                OnD05Changing(value);
                ReportPropertyChanging("D05");
                _D05 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D05");
                OnD05Changed();
            }
        }
        private global::System.String _D05;
        partial void OnD05Changing(global::System.String value);
        partial void OnD05Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D06
        {
            get
            {
                return _D06;
            }
            set
            {
                OnD06Changing(value);
                ReportPropertyChanging("D06");
                _D06 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D06");
                OnD06Changed();
            }
        }
        private global::System.String _D06;
        partial void OnD06Changing(global::System.String value);
        partial void OnD06Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D07
        {
            get
            {
                return _D07;
            }
            set
            {
                OnD07Changing(value);
                ReportPropertyChanging("D07");
                _D07 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D07");
                OnD07Changed();
            }
        }
        private global::System.String _D07;
        partial void OnD07Changing(global::System.String value);
        partial void OnD07Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D08
        {
            get
            {
                return _D08;
            }
            set
            {
                OnD08Changing(value);
                ReportPropertyChanging("D08");
                _D08 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D08");
                OnD08Changed();
            }
        }
        private global::System.String _D08;
        partial void OnD08Changing(global::System.String value);
        partial void OnD08Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D09
        {
            get
            {
                return _D09;
            }
            set
            {
                OnD09Changing(value);
                ReportPropertyChanging("D09");
                _D09 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D09");
                OnD09Changed();
            }
        }
        private global::System.String _D09;
        partial void OnD09Changing(global::System.String value);
        partial void OnD09Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String D10
        {
            get
            {
                return _D10;
            }
            set
            {
                OnD10Changing(value);
                ReportPropertyChanging("D10");
                _D10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("D10");
                OnD10Changed();
            }
        }
        private global::System.String _D10;
        partial void OnD10Changing(global::System.String value);
        partial void OnD10Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte D99
        {
            get
            {
                return _D99;
            }
            set
            {
                OnD99Changing(value);
                ReportPropertyChanging("D99");
                _D99 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D99");
                OnD99Changed();
            }
        }
        private global::System.Byte _D99;
        partial void OnD99Changing(global::System.Byte value);
        partial void OnD99Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DD3
        {
            get
            {
                return _DD3;
            }
            set
            {
                OnDD3Changing(value);
                ReportPropertyChanging("DD3");
                _DD3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DD3");
                OnDD3Changed();
            }
        }
        private global::System.String _DD3;
        partial void OnDD3Changing(global::System.String value);
        partial void OnDD3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DD4
        {
            get
            {
                return _DD4;
            }
            set
            {
                OnDD4Changing(value);
                ReportPropertyChanging("DD4");
                _DD4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DD4");
                OnDD4Changed();
            }
        }
        private global::System.String _DD4;
        partial void OnDD4Changing(global::System.String value);
        partial void OnDD4Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="SX01_AREA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SX01_AREA : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SX01_AREA 对象。
        /// </summary>
        /// <param name="zIZOINDEX">ZIZOINDEX 属性的初始值。</param>
        /// <param name="aREACODE">AREACODE 属性的初始值。</param>
        /// <param name="aREAPCODE">AREAPCODE 属性的初始值。</param>
        /// <param name="aREANAME">AREANAME 属性的初始值。</param>
        /// <param name="lEVEL">LEVEL 属性的初始值。</param>
        public static SX01_AREA CreateSX01_AREA(global::System.Int32 zIZOINDEX, global::System.String aREACODE, global::System.String aREAPCODE, global::System.String aREANAME, global::System.Int32 lEVEL)
        {
            SX01_AREA sX01_AREA = new SX01_AREA();
            sX01_AREA.ZIZOINDEX = zIZOINDEX;
            sX01_AREA.AREACODE = aREACODE;
            sX01_AREA.AREAPCODE = aREAPCODE;
            sX01_AREA.AREANAME = aREANAME;
            sX01_AREA.LEVEL = lEVEL;
            return sX01_AREA;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZIZOINDEX
        {
            get
            {
                return _ZIZOINDEX;
            }
            set
            {
                if (_ZIZOINDEX != value)
                {
                    OnZIZOINDEXChanging(value);
                    ReportPropertyChanging("ZIZOINDEX");
                    _ZIZOINDEX = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ZIZOINDEX");
                    OnZIZOINDEXChanged();
                }
            }
        }
        private global::System.Int32 _ZIZOINDEX;
        partial void OnZIZOINDEXChanging(global::System.Int32 value);
        partial void OnZIZOINDEXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AREACODE
        {
            get
            {
                return _AREACODE;
            }
            set
            {
                OnAREACODEChanging(value);
                ReportPropertyChanging("AREACODE");
                _AREACODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AREACODE");
                OnAREACODEChanged();
            }
        }
        private global::System.String _AREACODE;
        partial void OnAREACODEChanging(global::System.String value);
        partial void OnAREACODEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AREAPCODE
        {
            get
            {
                return _AREAPCODE;
            }
            set
            {
                OnAREAPCODEChanging(value);
                ReportPropertyChanging("AREAPCODE");
                _AREAPCODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AREAPCODE");
                OnAREAPCODEChanged();
            }
        }
        private global::System.String _AREAPCODE;
        partial void OnAREAPCODEChanging(global::System.String value);
        partial void OnAREAPCODEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AREANAME
        {
            get
            {
                return _AREANAME;
            }
            set
            {
                OnAREANAMEChanging(value);
                ReportPropertyChanging("AREANAME");
                _AREANAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AREANAME");
                OnAREANAMEChanged();
            }
        }
        private global::System.String _AREANAME;
        partial void OnAREANAMEChanging(global::System.String value);
        partial void OnAREANAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LEVEL
        {
            get
            {
                return _LEVEL;
            }
            set
            {
                OnLEVELChanging(value);
                ReportPropertyChanging("LEVEL");
                _LEVEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LEVEL");
                OnLEVELChanged();
            }
        }
        private global::System.Int32 _LEVEL;
        partial void OnLEVELChanging(global::System.Int32 value);
        partial void OnLEVELChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NSCModel", "FK_SX02_USER_SX01_AREA", "SX02_USER")]
        public EntityCollection<SX02_USER> SX02_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SX02_USER>("NSCModel.FK_SX02_USER_SX01_AREA", "SX02_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SX02_USER>("NSCModel.FK_SX02_USER_SX01_AREA", "SX02_USER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="SX02_USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SX02_USER : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SX02_USER 对象。
        /// </summary>
        /// <param name="zIZOINDEX">ZIZOINDEX 属性的初始值。</param>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="pW">PW 属性的初始值。</param>
        /// <param name="nAME">NAME 属性的初始值。</param>
        /// <param name="aREAINDEX">AREAINDEX 属性的初始值。</param>
        /// <param name="dEPTINDEX">DEPTINDEX 属性的初始值。</param>
        /// <param name="sTATE">STATE 属性的初始值。</param>
        public static SX02_USER CreateSX02_USER(global::System.Int32 zIZOINDEX, global::System.String id, global::System.String pW, global::System.String nAME, global::System.Int32 aREAINDEX, global::System.Int32 dEPTINDEX, global::System.Boolean sTATE)
        {
            SX02_USER sX02_USER = new SX02_USER();
            sX02_USER.ZIZOINDEX = zIZOINDEX;
            sX02_USER.ID = id;
            sX02_USER.PW = pW;
            sX02_USER.NAME = nAME;
            sX02_USER.AREAINDEX = aREAINDEX;
            sX02_USER.DEPTINDEX = dEPTINDEX;
            sX02_USER.STATE = sTATE;
            return sX02_USER;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZIZOINDEX
        {
            get
            {
                return _ZIZOINDEX;
            }
            set
            {
                if (_ZIZOINDEX != value)
                {
                    OnZIZOINDEXChanging(value);
                    ReportPropertyChanging("ZIZOINDEX");
                    _ZIZOINDEX = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ZIZOINDEX");
                    OnZIZOINDEXChanged();
                }
            }
        }
        private global::System.Int32 _ZIZOINDEX;
        partial void OnZIZOINDEXChanging(global::System.Int32 value);
        partial void OnZIZOINDEXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PW
        {
            get
            {
                return _PW;
            }
            set
            {
                OnPWChanging(value);
                ReportPropertyChanging("PW");
                _PW = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PW");
                OnPWChanged();
            }
        }
        private global::System.String _PW;
        partial void OnPWChanging(global::System.String value);
        partial void OnPWChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AREAINDEX
        {
            get
            {
                return _AREAINDEX;
            }
            set
            {
                OnAREAINDEXChanging(value);
                ReportPropertyChanging("AREAINDEX");
                _AREAINDEX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AREAINDEX");
                OnAREAINDEXChanged();
            }
        }
        private global::System.Int32 _AREAINDEX;
        partial void OnAREAINDEXChanging(global::System.Int32 value);
        partial void OnAREAINDEXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DEPTINDEX
        {
            get
            {
                return _DEPTINDEX;
            }
            set
            {
                OnDEPTINDEXChanging(value);
                ReportPropertyChanging("DEPTINDEX");
                _DEPTINDEX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEPTINDEX");
                OnDEPTINDEXChanged();
            }
        }
        private global::System.Int32 _DEPTINDEX;
        partial void OnDEPTINDEXChanging(global::System.Int32 value);
        partial void OnDEPTINDEXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean STATE
        {
            get
            {
                return _STATE;
            }
            set
            {
                OnSTATEChanging(value);
                ReportPropertyChanging("STATE");
                _STATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STATE");
                OnSTATEChanged();
            }
        }
        private global::System.Boolean _STATE;
        partial void OnSTATEChanging(global::System.Boolean value);
        partial void OnSTATEChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NSCModel", "FK_SX02_USER_SX01_AREA", "SX01_AREA")]
        public SX01_AREA SX01_AREA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SX01_AREA>("NSCModel.FK_SX02_USER_SX01_AREA", "SX01_AREA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SX01_AREA>("NSCModel.FK_SX02_USER_SX01_AREA", "SX01_AREA").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SX01_AREA> SX01_AREAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SX01_AREA>("NSCModel.FK_SX02_USER_SX01_AREA", "SX01_AREA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SX01_AREA>("NSCModel.FK_SX02_USER_SX01_AREA", "SX01_AREA", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NSCModel", "FK_SX02_USER_SX03_DEPT", "SX03_DEPT")]
        public SX03_DEPT SX03_DEPT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SX03_DEPT>("NSCModel.FK_SX02_USER_SX03_DEPT", "SX03_DEPT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SX03_DEPT>("NSCModel.FK_SX02_USER_SX03_DEPT", "SX03_DEPT").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SX03_DEPT> SX03_DEPTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SX03_DEPT>("NSCModel.FK_SX02_USER_SX03_DEPT", "SX03_DEPT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SX03_DEPT>("NSCModel.FK_SX02_USER_SX03_DEPT", "SX03_DEPT", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="SX03_DEPT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SX03_DEPT : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SX03_DEPT 对象。
        /// </summary>
        /// <param name="zIZOINDEX">ZIZOINDEX 属性的初始值。</param>
        /// <param name="dEPTCODE">DEPTCODE 属性的初始值。</param>
        /// <param name="dEPTNAME">DEPTNAME 属性的初始值。</param>
        public static SX03_DEPT CreateSX03_DEPT(global::System.Int32 zIZOINDEX, global::System.String dEPTCODE, global::System.String dEPTNAME)
        {
            SX03_DEPT sX03_DEPT = new SX03_DEPT();
            sX03_DEPT.ZIZOINDEX = zIZOINDEX;
            sX03_DEPT.DEPTCODE = dEPTCODE;
            sX03_DEPT.DEPTNAME = dEPTNAME;
            return sX03_DEPT;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZIZOINDEX
        {
            get
            {
                return _ZIZOINDEX;
            }
            set
            {
                if (_ZIZOINDEX != value)
                {
                    OnZIZOINDEXChanging(value);
                    ReportPropertyChanging("ZIZOINDEX");
                    _ZIZOINDEX = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ZIZOINDEX");
                    OnZIZOINDEXChanged();
                }
            }
        }
        private global::System.Int32 _ZIZOINDEX;
        partial void OnZIZOINDEXChanging(global::System.Int32 value);
        partial void OnZIZOINDEXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DEPTCODE
        {
            get
            {
                return _DEPTCODE;
            }
            set
            {
                OnDEPTCODEChanging(value);
                ReportPropertyChanging("DEPTCODE");
                _DEPTCODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DEPTCODE");
                OnDEPTCODEChanged();
            }
        }
        private global::System.String _DEPTCODE;
        partial void OnDEPTCODEChanging(global::System.String value);
        partial void OnDEPTCODEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DEPTNAME
        {
            get
            {
                return _DEPTNAME;
            }
            set
            {
                OnDEPTNAMEChanging(value);
                ReportPropertyChanging("DEPTNAME");
                _DEPTNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DEPTNAME");
                OnDEPTNAMEChanged();
            }
        }
        private global::System.String _DEPTNAME;
        partial void OnDEPTNAMEChanging(global::System.String value);
        partial void OnDEPTNAMEChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NSCModel", "FK_SX02_USER_SX03_DEPT", "SX02_USER")]
        public EntityCollection<SX02_USER> SX02_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SX02_USER>("NSCModel.FK_SX02_USER_SX03_DEPT", "SX02_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SX02_USER>("NSCModel.FK_SX02_USER_SX03_DEPT", "SX02_USER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NSCModel", Name="SX04_SYS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SX04_SYS : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SX04_SYS 对象。
        /// </summary>
        /// <param name="zIZOINDEX">ZIZOINDEX 属性的初始值。</param>
        /// <param name="fILEPATH">FILEPATH 属性的初始值。</param>
        /// <param name="fILEURL">FILEURL 属性的初始值。</param>
        /// <param name="mD5">MD5 属性的初始值。</param>
        public static SX04_SYS CreateSX04_SYS(global::System.Int32 zIZOINDEX, global::System.String fILEPATH, global::System.String fILEURL, global::System.String mD5)
        {
            SX04_SYS sX04_SYS = new SX04_SYS();
            sX04_SYS.ZIZOINDEX = zIZOINDEX;
            sX04_SYS.FILEPATH = fILEPATH;
            sX04_SYS.FILEURL = fILEURL;
            sX04_SYS.MD5 = mD5;
            return sX04_SYS;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZIZOINDEX
        {
            get
            {
                return _ZIZOINDEX;
            }
            set
            {
                if (_ZIZOINDEX != value)
                {
                    OnZIZOINDEXChanging(value);
                    ReportPropertyChanging("ZIZOINDEX");
                    _ZIZOINDEX = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ZIZOINDEX");
                    OnZIZOINDEXChanged();
                }
            }
        }
        private global::System.Int32 _ZIZOINDEX;
        partial void OnZIZOINDEXChanging(global::System.Int32 value);
        partial void OnZIZOINDEXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FILEPATH
        {
            get
            {
                return _FILEPATH;
            }
            set
            {
                OnFILEPATHChanging(value);
                ReportPropertyChanging("FILEPATH");
                _FILEPATH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FILEPATH");
                OnFILEPATHChanged();
            }
        }
        private global::System.String _FILEPATH;
        partial void OnFILEPATHChanging(global::System.String value);
        partial void OnFILEPATHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FILEURL
        {
            get
            {
                return _FILEURL;
            }
            set
            {
                OnFILEURLChanging(value);
                ReportPropertyChanging("FILEURL");
                _FILEURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FILEURL");
                OnFILEURLChanged();
            }
        }
        private global::System.String _FILEURL;
        partial void OnFILEURLChanging(global::System.String value);
        partial void OnFILEURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MD5
        {
            get
            {
                return _MD5;
            }
            set
            {
                OnMD5Changing(value);
                ReportPropertyChanging("MD5");
                _MD5 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MD5");
                OnMD5Changed();
            }
        }
        private global::System.String _MD5;
        partial void OnMD5Changing(global::System.String value);
        partial void OnMD5Changed();

        #endregion

    
    }

    #endregion

    
}
